# Generated by Django 5.1 on 2024-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='circulante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passivo',
            name='circulante',
            field=models.BooleanField(default=True),
        ),
    ]
