# Generated by Django 5.1 on 2024-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_ativo_circulante_passivo_circulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemonstracaoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Demonstração de Resultados',
                'verbose_name_plural': 'Demonstrações de Resultados',
            },
        ),
    ]
