# Generated by Django 5.1 on 2024-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_demonstracaoresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstracaoresultado',
            name='receita',
            field=models.BooleanField(default=True, null=True, verbose_name='Receita'),
        ),
    ]
